# Generated by Django 4.1.2 on 2022-10-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64)),
                ('status', models.SmallIntegerField(choices=[(0, 'To do'), (1, 'In progress'), (2, 'Done')], default=0)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
